# Generated by Django 6.0.6 on 2026-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="categoria",
            field=models.CharField(default="Geral", max_length=50),
        ),
        migrations.AddField(
            model_name="noticia",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
    ]
