# Generated by Django 6.0.6 on 2026-06-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_crise"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="destaque",
            field=models.BooleanField(default=False),
        ),
    ]
