# Generated by Django 6.0.6 on 2026-06-27 15:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_noticia_destaque"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="diario",
            name="data",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="diario",
            name="humor",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="diario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
