# Generated by Django 6.0.6 on 2026-07-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_diario_data_alter_diario_humor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dica",
            name="categoria",
            field=models.CharField(default="Geral", max_length=50),
        ),
    ]
