# Generated by Django 6.0.6 on 2026-07-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dica_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercicio",
            name="tipo",
            field=models.CharField(default="Respiracao", max_length=30),
        ),
    ]
